# Generated by Django 4.2.2 on 2023-06-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('forks_count', models.IntegerField(blank=True, default=0, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_login', models.CharField(max_length=39, unique=True)),
                ('github_created_at', models.CharField(max_length=50, unique=True)),
                ('github_id', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('followers_count', models.IntegerField(blank=True, default=0, null=True)),
                ('hireable', models.BooleanField(blank=True, default=False, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=15, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('blog', models.URLField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=160, null=True)),
                ('company', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('repo', models.ManyToManyField(to='main.repo')),
            ],
        ),
    ]
