# Generated by Django 4.2.2 on 2023-06-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='repo',
            new_name='repos',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='github_id',
        ),
    ]
