# Generated by Django 4.2.2 on 2023-06-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contributor_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='blog',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='github_created_at',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='location',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
