# Generated by Django 4.2.2 on 2023-06-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contributor_avatar_url_alter_contributor_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
